import React, { useEffect, useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { CalculationResult, ProductType } from '../types';
import { Bot, Sparkles, AlertCircle } from 'lucide-react';

interface Props {
  results: {
    steel: CalculationResult | null;
    pv: CalculationResult | null;
    car: CalculationResult | null;
  };
}

const GeminiAdvisor: React.FC<Props> = ({ results }) => {
  const [advice, setAdvice] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAdvice = async () => {
      if (!results.steel || !results.pv || !results.car) return;
      if (!process.env.API_KEY) {
         setAdvice("Please configure the API_KEY environment variable to enable AI insights.");
         return;
      }

      setLoading(true);
      setError(null);

      try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        
        const prompt = `
          Based on the following international trade optimization data between China (Seller) and Foreign (Buyer), provide a strategic recommendation.
          Identify the product with the highest Joint Total Profit and highlight any risks or opportunities. 
          Keep the response concise (max 200 words), professional, and use bullet points. Format in simple Markdown.
          
          Data:
          1. Steel: Best Qty ${results.steel.quantity}, Joint Profit $${results.steel.jointTotalProfitUSD.toFixed(2)}, Container Utilization ${results.steel.containerUtilization.toFixed(1)}%.
          2. PV: Best Qty ${results.pv.quantity}, Joint Profit $${results.pv.jointTotalProfitUSD.toFixed(2)}, Container Utilization ${results.pv.containerUtilization.toFixed(1)}%.
          3. Car: Best Qty ${results.car.quantity}, Joint Profit $${results.car.jointTotalProfitUSD.toFixed(2)}, Container Utilization ${results.car.containerUtilization.toFixed(1)}%.
          
          Compare them and suggest the best allocation of funds.
        `;

        const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash',
          contents: prompt,
        });

        setAdvice(response.text);
      } catch (err) {
        console.error("Gemini API Error:", err);
        setError("AI Service temporarily unavailable.");
      } finally {
        setLoading(false);
      }
    };

    fetchAdvice();
  }, [results.steel, results.pv, results.car]);

  return (
    <div className="bg-gradient-to-br from-indigo-600 to-purple-700 text-white rounded-2xl p-6 shadow-xl relative overflow-hidden">
      <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -translate-y-16 translate-x-16 blur-2xl"></div>
      
      <div className="flex items-center gap-3 mb-4 relative z-10">
        <Bot className="w-8 h-8 text-indigo-200" />
        <h3 className="text-xl font-bold">AI 智能决策顾问 (Gemini Powered)</h3>
      </div>

      <div className="relative z-10 bg-black/20 rounded-xl p-4 min-h-[120px]">
        {loading ? (
          <div className="flex items-center justify-center h-full gap-2 text-indigo-200 animate-pulse">
            <Sparkles className="w-5 h-5" /> 正在分析最优解...
          </div>
        ) : error ? (
           <div className="flex items-center gap-2 text-rose-300">
             <AlertCircle className="w-5 h-5" /> {error}
           </div>
        ) : (
          <div className="prose prose-invert prose-sm max-w-none">
             {advice.split('\n').map((line, i) => (
                <p key={i} className="mb-1 leading-relaxed">{line}</p>
             ))}
          </div>
        )}
      </div>
      
      <div className="mt-4 text-xs text-indigo-200/60 text-right">
        Generated by Google Gemini 2.5 Flash
      </div>
    </div>
  );
};

export default GeminiAdvisor;
